@extends('layouts.storefront')

@section('title', 'Lumière Jewelry — Vẻ đẹp lưu dấu')

@section('content')
<div class="announcement"><div class="container announcement__inner"><span>✦ Miễn phí vận chuyển cho đơn từ 2.000.000đ</span><span class="announcement__right">Hotline: 1900 6868 <i></i> Theo dõi chúng tôi trên Instagram</span></div></div>

<header class="site-header">
    <div class="container site-header__main">
        <button class="menu-toggle" aria-label="Mở menu">☰</button>
        <a href="#" class="brand"><img src="{{ asset('assets/storefront/store-logo.png') }}" alt="Lumière Jewelry"></a>
        <form class="search"><input type="search" placeholder="Tìm kiếm trang sức..." aria-label="Tìm kiếm"><button aria-label="Tìm kiếm">⌕</button></form>
        <div class="header-tools"><a href="#" aria-label="Yêu thích">♡ <small>Yêu thích</small></a><a href="#" aria-label="Tài khoản">♙ <small>Tài khoản</small></a><a href="#" class="cart" aria-label="Giỏ hàng">♧ <small>Giỏ hàng</small><b>0</b></a></div>
    </div>
    <nav class="main-nav"><div class="container main-nav__inner"><button class="all-categories">☷ <span>Tất cả danh mục</span></button><div class="nav-links"><a class="active" href="#top">Trang chủ</a><a href="#products">Cửa hàng</a><a href="#gifts">Quà tặng</a><a href="#categories">Bông tai</a><a href="#products">Nhẫn</a><a href="#stories">Về chúng tôi</a><a href="#newsletter">Liên hệ</a></div></div></nav>
</header>

<main id="top">
<section class="hero" aria-label="Bộ sưu tập nổi bật">
    <div class="hero__slides">
        <article class="hero__slide is-active"><img src="{{ asset('assets/storefront/hero-1.png') }}" alt="Bộ sưu tập trang sức vàng"><div class="hero__copy"><p class="eyebrow">Bộ sưu tập mới · 2024</p><h1>Vẻ đẹp<br><em>lưu dấu</em></h1><p class="hero__description">Những thiết kế tinh xảo được tạo nên<br>để kể câu chuyện riêng của bạn.</p><a class="button button--dark" href="#products">Mua ngay <span>↗</span></a></div></article>
        <article class="hero__slide"><img src="{{ asset('assets/storefront/hero-2.png') }}" alt="Trang sức thanh lịch"><div class="hero__copy"><p class="eyebrow">Ánh sáng riêng của bạn</p><h1>Chạm vào<br><em>ánh sáng</em></h1><p class="hero__description">Vẻ lấp lánh vượt thời gian, dành cho<br>những khoảnh khắc không thể quên.</p><a class="button button--dark" href="#products">Khám phá <span>↗</span></a></div></article>
        <article class="hero__slide"><img src="{{ asset('assets/storefront/hero-3.png') }}" alt="Trang sức dành cho nàng"><div class="hero__copy"><p class="eyebrow">Dành riêng cho nàng</p><h1>Điều đẹp đẽ<br><em>nhất</em></h1><p class="hero__description">Một món quà nhỏ, một yêu thương thật lớn.</p><a class="button button--dark" href="#gifts">Tặng nàng <span>↗</span></a></div></article>
        <article class="hero__slide"><img src="{{ asset('assets/storefront/hero-4.png') }}" alt="Trang sức kim cương"><div class="hero__copy"><p class="eyebrow">Tinh hoa kim cương</p><h1>Toả sáng<br><em>cùng em</em></h1><p class="hero__description">Khẳng định phong cách bằng vẻ đẹp thuần khiết.</p><a class="button button--dark" href="#products">Mua ngay <span>↗</span></a></div></article>
    </div><button class="hero__arrow hero__arrow--prev" aria-label="Ảnh trước">←</button><button class="hero__arrow hero__arrow--next" aria-label="Ảnh tiếp">→</button><div class="hero__dots"></div>
</section>

<section class="section categories" id="categories"><div class="container"><div class="section-heading"><p class="eyebrow">Khám phá bộ sưu tập</p><h2>Chọn phong cách <em>hoàn hảo</em></h2><p>Những món trang sức được tuyển chọn để đồng hành cùng bạn.</p></div><div class="category-grid">
@foreach ([['cat-bangles.jpg','Lắc'],['cat-bracelets.jpg','Vòng tay'],['cat-brooch.jpg','Trâm cài'],['cat-chains.jpg','Dây chuyền kiểu'],['cat-earrings.jpg','Bông tai'],['cat-rings.jpg','Nhẫn'],['cat-gifting.jpg','Quà tặng'],['cat-mangalsutra.jpg','Vòng truyền thống'],['cat-necklace.jpg','Dây chuyền'],['cat-nosepin.jpg','Khuyên mũi']] as $category)<a class="category-card" href="#products"><div><img src="{{ asset('assets/storefront/'.$category[0]) }}" alt="{{ $category[1] }}"></div><span>{{ $category[1] }}</span><b>↗</b></a>@endforeach
</div></div></section>

@php $products = [['prod-nislconuat.jpg','Nhẫn Nguyện Ước','2.850.000đ','sale'],['prod-blandit.jpg','Bông tai Ngọc Sương','1.690.000đ',''],['prod-iaculis.jpg','Dây chuyền Ánh Trăng','3.420.000đ','sale'],['prod-maximus.jpg','Vòng tay Tình Yêu','2.190.000đ',''],['prod-namhit.jpg','Nhẫn Hoa Ban Mai','1.980.000đ','new'],['prod-velitaq.jpg','Mặt dây Thanh Xuân','2.650.000đ',''],['prod-tcumsan.jpg','Bông tai Nụ Hôn','1.450.000đ','sale'],['prod-adipisng.jpg','Lắc tay Dịu Dàng','2.780.000đ',''],['prod-acellus.jpg','Nhẫn Kim Cương Mộng Mơ','5.900.000đ','new'],['prod-atiquam.jpg','Dây chuyền Cánh Bướm','3.150.000đ',''],['prod-semper.jpg','Vòng tay Bình Yên','1.890.000đ','sale'],['prod-aptent.jpg','Bông tai Ngôi Sao','1.250.000đ','']]; @endphp
<section class="section products" id="products"><div class="container"><div class="section-heading section-heading--row"><div><p class="eyebrow">Lựa chọn của nàng</p><h2>Sản phẩm <em>nổi bật</em></h2></div><a class="text-link" href="#">Xem tất cả sản phẩm ↗</a></div><div class="product-grid">@foreach($products as $product)<article class="product-card"><div class="product-card__image"><img src="{{ asset('assets/storefront/'.$product[0]) }}" alt="{{ $product[1] }}">@if($product[3])<span class="badge">{{ $product[3] === 'sale' ? 'Ưu đãi' : 'Mới' }}</span>@endif<button class="heart" aria-label="Thêm vào yêu thích">♡</button><div class="product-card__actions"><button>Xem nhanh</button><button>Thêm vào giỏ</button></div></div><div class="product-card__info"><p>Lumière Jewelry</p><h3>{{ $product[1] }}</h3><strong>{{ $product[2] }}</strong></div></article>@endforeach</div></div></section>

<section class="occasion section"><div class="container"><div class="section-heading"><p class="eyebrow">Cảm hứng bất tận</p><h2>Thế giới trang sức — <em>Hoàn hảo mọi dịp</em></h2></div><div class="occasion-tabs"><button class="is-active">Cưới hỏi</button><button>Vàng</button><button>Kim cương</button><button>Đeo hằng ngày</button></div><div class="occasion-grid">@foreach([['occasion-wedding.jpg','Ngày trọng đại'],['occasion-gold.jpg','Sắc vàng kiêu hãnh'],['occasion-diamond.jpg','Khoảnh khắc rực rỡ'],['occasion-daily.jpg','Đẹp mỗi ngày']] as $occasion)<a href="#products"><img src="{{ asset('assets/storefront/'.$occasion[0]) }}" alt="{{ $occasion[1] }}"><span>{{ $occasion[1] }} <b>↗</b></span></a>@endforeach</div></div></section>

<section class="gifts section" id="gifts"><div class="container"><div class="section-heading section-heading--row"><div><p class="eyebrow">Trao gửi yêu thương</p><h2>Gói trọn <em>yêu thương</em></h2></div><a class="text-link" href="#">Khám phá quà tặng ↗</a></div><div class="gift-grid">@foreach([['gift-wrap.png','Hộp quà đặc biệt'],['gift-rings.jpg','Nhẫn dành cho nàng'],['gift-kundan.jpg','Vẻ đẹp truyền thống'],['gift-jewellery.jpg','Bộ trang sức'],['gift-pendants.jpg','Mặt dây ý nghĩa'],['gift-mom.jpg','Tặng mẹ yêu'],['gift-custom.jpg','Quà tặng riêng bạn']] as $gift)<a href="#products"><img src="{{ asset('assets/storefront/'.$gift[0]) }}" alt="{{ $gift[1] }}"><span>{{ $gift[1] }}</span></a>@endforeach</div></div></section>

<section class="trust"><div class="container trust__grid"><div><b>100%</b><span>Chứng nhận<br>chất lượng</span></div><div><b>15</b><span>Ngày đổi trả<br>miễn phí</span></div><div><b>∞</b><span>Đổi trọn đời<br>miễn phí</span></div><div><b>01</b><span>Năm bảo hành<br>tận tâm</span></div></div></section>

<section class="section products products--new"><div class="container"><div class="section-heading section-heading--row"><div><p class="eyebrow">Vừa cập bến</p><h2>Sản phẩm <em>mới</em></h2></div><a class="text-link" href="#">Xem tất cả ↗</a></div><div class="product-grid product-grid--four">@foreach(array_slice($products, 4, 4) as $product)<article class="product-card"><div class="product-card__image"><img src="{{ asset('assets/storefront/'.$product[0]) }}" alt="{{ $product[1] }}"><span class="badge">Mới</span><button class="heart">♡</button><div class="product-card__actions"><button>Xem nhanh</button><button>Thêm vào giỏ</button></div></div><div class="product-card__info"><p>Lumière Jewelry</p><h3>{{ $product[1] }}</h3><strong>{{ $product[2] }}</strong></div></article>@endforeach</div></div></section>

<section class="stories section" id="stories"><div class="container"><div class="section-heading"><p class="eyebrow">Lời thì thầm của khách hàng</p><h2>Câu chuyện <em>từ bạn</em></h2></div><div class="stories-grid">@foreach([['“Món quà cưới thật tinh tế. Từ hộp quà đến từng chi tiết đều khiến mình mỉm cười.”','Minh Anh · Hà Nội'],['“Nhân viên tư vấn rất có tâm, chiếc nhẫn vừa vặn và đẹp hơn cả mong đợi.”','Thuỳ Dương · Đà Nẵng'],['“Mình đã tìm thấy món quà hoàn hảo cho mẹ. Mẹ rất yêu thích!”','Ngọc Mai · TP. Hồ Chí Minh'],['“Trang sức Lumière giúp mỗi ngày của mình thêm một chút lấp lánh.”','Khánh Linh · Hà Nội']] as $story)<blockquote><span>“</span><p>{{ $story[0] }}</p><footer>{{ $story[1] }} <b>★★★★★</b></footer></blockquote>@endforeach</div></div></section>

<section class="instagram"><div class="container"><div class="section-heading"><p class="eyebrow">@lumiere.jewelry</p><h2>Theo dõi <em>ánh sáng</em></h2></div><div class="instagram-grid">@for($i=1;$i<=8;$i++)<a href="#"><img src="{{ asset('assets/storefront/insta-'.$i.'.jpg') }}" alt="Khoảnh khắc cùng Lumière"></a>@endfor</div></div></section>
<section class="services"><div class="container services__grid"><div><b>✧</b><span><strong>Miễn phí vận chuyển</strong>Cho đơn từ 2.000.000đ</span></div><div><b>◈</b><span><strong>Thanh toán linh hoạt</strong>An tâm với mọi lựa chọn</span></div><div><b>↻</b><span><strong>Đổi trả dễ dàng</strong>Trong vòng 15 ngày</span></div><div><b>♧</b><span><strong>Hỗ trợ tận tâm</strong>Luôn sẵn sàng lắng nghe</span></div></div></section>
<section class="newsletter" id="newsletter"><div class="container newsletter__inner"><div><p class="eyebrow">Lumière journal</p><h2>Đăng ký nhận <em>tin mới</em></h2><p>Đừng bỏ lỡ những câu chuyện đẹp và ưu đãi dành riêng cho bạn.</p></div><form><input type="email" placeholder="Địa chỉ email của bạn" aria-label="Địa chỉ email"><button class="button button--light">Đăng ký <span>↗</span></button></form></div></section>
</main>
<footer class="footer"><div class="container footer__grid"><div class="footer__brand"><img src="{{ asset('assets/storefront/store-logo.png') }}" alt="Lumière Jewelry"><p>Trang sức kể câu chuyện riêng của bạn.</p><address>28 Lê Thái Tổ, Hoàn Kiếm<br>Hà Nội, Việt Nam</address><div class="social">Instagram &nbsp; Facebook &nbsp; Pinterest</div></div><div><h4>Công ty</h4><a href="#">Về Lumière</a><a href="#">Câu chuyện thương hiệu</a><a href="#">Tuyển dụng</a><a href="#">Liên hệ</a></div><div><h4>Hỗ trợ</h4><a href="#">Hướng dẫn mua hàng</a><a href="#">Chính sách đổi trả</a><a href="#">Bảo hành</a><a href="#">Câu hỏi thường gặp</a></div><div><h4>Theo dõi</h4><a href="#">Instagram</a><a href="#">Facebook</a><a href="#">Pinterest</a><a href="#">Zalo</a></div></div><div class="container footer__bottom"><span>© 2024 Lumière Jewelry. Thủ công với yêu thương.</span><span>Điều khoản &nbsp; Chính sách bảo mật</span></div></footer>
@endsection
